# Use the official MySQL image as the base image
FROM mysql:8

# Set environment variables
ENV MYSQL_DATABASE=technical \
    MYSQL_USER=sail \
    MYSQL_PASSWORD=mpassword\
    MYSQL_ROOT_PASSWORD=rootpassword

# Expose port 3306 for MySQL
EXPOSE 3306
